user.kafka.stream-lifecycle-topic=kafka-stream-test-topic
user.kafka.recording-lifecycle-topic=kafka-recording-test-topic
user.kafka.recording-part-lifecycle-topic=kafka-recording-part-test-topic
user.kafka.group-id=kafka-test-group
spring.kafka.bootstrap-servers=localhost:9092

spring.rabbitmq.username=testRabbitUser
spring.rabbitmq.password=testRabbitPassword
spring.rabbitmq.host=testRabbitHost
spring.rabbitmq.port=12345

user.rabbitmq.recording-queue.name=rabbitmq-recording-test-queue
user.rabbitmq.uploading-queue.name=rabbitmq-uploading-test-queue
user.rabbitmq.uploading-recorded-part-queue.name=rabbitmq-uploading-recorded-part-test-queue

otel.traces.exporter=none
otel.metrics.exporter=none
otel.logs.exporter=none