CREATE TABLE IF NOT EXISTS event_logs (
    id UUID PRIMARY KEY,
    status VARCHAR(100) NOT NULL, -- PENDING, SENT_TO_BROKER
    event_type VARCHAR(100) NOT NULL, -- STREAM_STARTED, STREAM_ENDED
    payload JSONB NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);