spring.application.name=stream-status-service

server.port=8088

spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

user.kafka.topic-stream-lifecycle-events=${KAFKA_TOPIC_STREAM_LIFECYCLE:default-kafka-topic}
user.kafka.topic-recording-lifecycle-events=${KAFKA_TOPIC_RECORDING_LIFECYCLE:default-kafka-topic}
user.kafka.group-id=${STREAM_STATUS_KAFKA_GROUP_ID:default-group-id}

user.subscription-service.url=${SUBSCRIPTION_SERVICE_URL:localhost:8087}